Environment: dev
ProjectName: testapp

VpcCidr: 10.0.0.0/16
PublicSubnet1Cidr: 10.0.1.0/24
PublicSubnet2Cidr: 10.0.2.0/24
PrivateSubnet1Cidr: 10.0.11.0/24
PrivateSubnet2Cidr: 10.0.12.0/24
DbSubnet1Cidr: 10.0.21.0/24
DbSubnet2Cidr: 10.0.22.0/24

FrontendImageUrl: <account>.dkr.ecr.<region>.amazonaws.com/frontend:latest
BackendImageUrl: <account>.dkr.ecr.<region>.amazonaws.com/backend:latest

DesiredCount: 2
DbName: testdb
MasterUsername: admin
MasterPassword: changeMe123
AlarmEmail: you@example.com
