AWSTemplateFormatVersion: '2010-09-09'
Description: ECS Cluster

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${ProjectName}-${Environment}-cluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT

Outputs:
  ClusterName:
    Value: !Ref ECSCluster
