AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles for ECS

Resources:

  ################################
  # ECS EXECUTION ROLE
  ################################
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ################################
  # ECS TASK ROLE (APP ROLE)
  ################################
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ecsTaskRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole

Outputs:
  ECSExecutionRoleArn:
    Description: ARN of ECS Execution Role
    Value: !GetAtt ECSExecutionRole.Arn

  ECSTaskRoleArn:
    Description: ARN of ECS Task Role
    Value: !GetAtt ECSTaskRole.Arn
