AWSTemplateFormatVersion: '2010-09-09'
Description: CloudWatch Alarms

Parameters:
  AlarmEmail:
    Type: String

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref AlarmEmail
          Protocol: email
